name: build

on:
  workflow_dispatch: {}

jobs:

  renovate:
    runs-on: docker
    steps:
      - name: Create Kubeconfig
        run: |
          mkdir $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: kubernetes
          driver-opts: |
            namespace=gitea
            qemu.install=true
          config-inline: |
            [registry."192.168.6.10:5000"]
              http = true
              insecure = true

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: 192.168.6.10:5000/glauth/glauth:latest

